spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/
    hikari:
      catalog: framework
    username: root
    password: 1234
logging:
  config: classpath:conf/logback.xml